### ISSUE TITLE
ios is not work. pod install fail

### ISSUE THREAD

**Issue by AlonDeng** [Alwinator/react-native-http-bridge-refurbished#2]
[!] No podspec found for `react-native-http-bridge-refurbished` in `../node_modules/react-native-http-bridge-refurbished`

<img width="988" alt="image" src="https://user-images.githubusercontent.com/42921951/220950858-b4f71e63-772a-4121-bd7c-1922416d6a24.png">

Thanks for your contribution！

**Comment by Alwinator** [comment]
Thank you for reporting, I will fix it in the next days :)

**Comment by Alwinator** [comment]
@AlonDeng Unfortunately, I was not able to reproduce your issue. Can you please provide more details about the bug?

- Are you using the latest react-native-http-bridge-refurbished version?
- Which react-native version are you using?
- Which command are you trying to execute?
- Please provide the whole logs

**Comment by Alwinator** [comment]
@AlonDeng I will close this issue because there has been no response for the last 3 weeks. I assume that has been an application problem and you solved it. If the problem still exists, feel free to reopen this issue.
