### ISSUE TITLE
Blank screen on init - using expo

### ISSUE THREAD

**Issue by abdelhameedhamdy** [Alwinator/react-native-http-bridge-refurbished#22]
Hey, When trying to run the http server using expo, 

getting expo blank screen with no elements renders in both android and ios.

Should I eject from expo ? 

repo to reproduce issue:
https://github.com/abdelhameedhamdy/expo-http-server

Thanks

**Comment by Alwinator** [comment]
@abdelhameedhamdy Expo does not support libraries that include native Android/iOS code. This means that Expo does not support this library.
