### ISSUE TITLE
[iOS] request.data throws error because request.postData is empty

### ISSUE THREAD

**Issue by silencer07** [Alwinator/react-native-http-bridge-refurbished#32]
Basically this log tells the problem:

`req {"postData": undefined, "requestId": "1703322785794:568150", "type": "POST", "url": "/songs"}`

Note: before I have a workaround like this on ios 17.1 :

`const addSongReq: AddSongRequest = Platform.OS === "android" ? req.data : req.postData`

however when I updated my iOS version to 17.2.x, request is basically has empty postData

Note that this bug does not occur on android.

code that is doing a POST request to the server

```
const result = await fetch(`http://${get().ipAddress}/songs`, {
  method: "POST",
  body: JSON.stringify({
    id: escape(song.id),
    title: song.title,
    thumbnailUrl: song.thumbnailUrl,
    duration: song.duration,
  }),
});
```

**Comment by silencer07** [comment]
a side note that might be helpful: Basically I encountered this problem: https://github.com/damonwonghv/youtube-search-api/issues/28

What I did as a workaround in iOS is to copy-paste the code, and use `unescape-js` library to basically decode the encoded JSON string, then finally JSON.parse it.

I am thinking if maybe, in the native code in iOS, something like that needs to be done as well

**Comment by silencer07** [comment]
Found a workaround. Need to add this to javascript `fetch` configuration to work on iOS

```
headers: {
  "Content-Type": "application/json",
}
```

**Comment by ospfranco** [comment]
The workaround is not working for me, even when specifying the headers. This only happens with fetch, axios works normally.

![Oscar Franco Screen 001211](https://github.com/Alwinator/react-native-http-bridge-refurbished/assets/1634213/32b635f0-7bfd-4b94-a381-b6641cd70d20)
![Oscar Franco Screen 001212](https://github.com/Alwinator/react-native-http-bridge-refurbished/assets/1634213/b3ff43f4-01cb-49dc-8608-41de0296a0dd)

Any idea what might be the issue? @Alwinator
