### ISSUE TITLE
Cannot Read Property start of Null

### ISSUE THREAD

**Issue by lbabich** [Alwinator/react-native-http-bridge-refurbished#37]
Hi there,

Running react-native `0.73` with expo `50.0.6` 
When running expo start and then launching on an emulated android device I am getting an issue when trying to start up the server.  Fairly new to react native. But from what I have read it should do auto linking on this version? Or is there some extra work needed to get the Http native module working?

```js
	useEffect(() => {
		const server = new BridgeServer('http_service', true);
		server.get('/', async (req, res) => {
			return { message: 'OK' };
		});
		server.listen(8080);

		return () => {
			server.stop();
		};
	}, []);
```

![image](https://github.com/Alwinator/react-native-http-bridge-refurbished/assets/41468500/e516885a-cce6-4c4e-8fef-809cc349283d)

**Comment by Alwinator** [comment]
Please see https://github.com/Alwinator/react-native-http-bridge-refurbished/issues/28
